# CONFIGURAÇÃO DO SUPABASE (PostgreSQL)
spring.datasource.url=jdbc:postgresql://db.fgaqxsrehzzswdgmgpyv.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=FalcaoSombrio2026
spring.datasource.driver-class-name=org.postgresql.Driver

# FORÇAR O DIALETO DO HIBERNATE (Isso corrige o erro do log!)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# CONFIGURAÇÃO DO MONGO ATLAS (Mantendo a correção do %40 se a senha tiver @)
spring.data.mongodb.uri=mongodb+srv://rodello:10726960Vitor%40@darkfalconsystem.8xopcdy.mongodb.net/?appName=DarkFalconSystem

# Segurança
spring.security.user.name=admin
spring.security.user.password=1234