
spring.datasource.url=jdbc:postgresql://db.fgaqxsrehzzswdgmgpyv.supabase.co:5432/postgres

spring.datasource.username=postgres

spring.datasource.password=FalcaoSombrio2026



spring.data.mongodb.uri=mongodb+srv://rodello:10726960VITOR@darkfalconsystem.8xopcdy.mongodb.net/?appName=DarkFalconSystem

# Permite que o Spring sirva o login.html sem bloquear
spring.security.user.name=admin
spring.security.user.password=1234
