# ====================================================================
# CONFIGURAÇÃO DO SUPABASE (Pooler IPv4)
# ====================================================================
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.fgaqxsrehzzswdgmgpyv
spring.datasource.password=FalcaoSombrio2026
spring.datasource.driver-class-name=org.postgresql.Driver

# OBRIGATÓRIO PARA O POOLER: Limita e estabiliza as conexões
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000

# Força o dialeto correto para o Hibernate rodar liso
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ====================================================================
# CONFIGURAÇÃO DO MONGO ATLAS
# ====================================================================
spring.data.mongodb.uri=mongodb+srv://rodello:10726960Vitor%40@darkfalconsystem.8xopcdy.mongodb.net/?appName=DarkFalconSystem

# ====================================================================
# CONFIGURAÇÕES DE INFRAESTRUTURA & SEGURANÇA
# ====================================================================
server.port=${PORT:8080}

spring.security.user.name=admin
spring.security.user.password=1234