# ====================================================================
# CONFIGURAÇÃO DO SUPABASE (Conexão Direta para Localhost)
# ====================================================================
# Mudamos o host tirando o ".pooler" e usamos a porta padrão direta 5432 ou 6543 caso use o proxy deles. 
# No link direto, o seu usuário é APENAS "postgres", sem aquele sufixo do tenant.
spring.datasource.url=jdbc:postgresql://db.fgaqxsrehzzswdgmgpyv.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=FalcaoSombrio2026
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ====================================================================
# CONFIGURAÇÕES DE INFRAESTRUTURA & SEGURANÇA LOCAL
# ====================================================================
server.port=8080
